fsharp/fsharp.org

_layouts/default.html
index.html
technical-groups/index.md

Removed "affiliation" language for non-affiliated groups for legal reasons.

Rewording of Technical Groups page

---

guides/apps-and-games/index.md

The Xamarin Forms example link on this page is broken: http://fsharp.org/guides/apps-and-games/index.html

Fix the Xamarin Forms example link.

---

guides/apps-and-games/index.md

Make the Xamarin Forms link just a plain link, not an image link. Sorry, I missed this during my last pull request.

Make this a plain link.

---

_layouts/default.html
css/main.css

As we are moving towards formal F# Foundation structure, it is important to distinguish what is original F# org content and what are external links. This uses a neat CSS trick to make this visible:

Add icon for external links

---

community/projects/index.md

See: https://github.com/nessos/Vagabond/issues/1

Vagrant is now Vagabond due to naming collision

---

guides/math-and-statistics/index.md

Fmat: the license was not on a separate paragraph

Minor math-and-statistics formatting fix

---

community/projects/index.md

Hi! 
Please add a link to my simulation library Aivika for .NET. This is an F# port of my Haskell simulation library of the same name. It supports discrete event simulation, system dynamics and agent-based modeling. The library is released under a dual-license model: GPLv3 and Commercial. There is the PDF documentation, but it mostly describes a commercial version, although the engine itself is fully licensed under dual GPL/Commercial. The commercial version contains only additional modules that are needed for analysis of the results.
Thanks,
David Sorokin

Added a link to Aivika for .NET

---

community/projects/index.md

hi,
ive created a plugin for sonarqube that allows the import f# code, it uses fsharplint and fxcop.
Would it be possible to list it in the foundantion
Thanks and Regards
Jorge Costa

add sonarqube f# plugin

---

_layouts/default.html
guides/slack/index.md
index.html

Since joining Slack teams is slightly more complicated than a simple link on index.html, I created another page that briefly describes the benefits of Slack, and a link to that page under the Contribute dropdown menu.

Added F# on Slack page

---

use/windows/index.md

The installation path is different on 32-bit and 64-bit Windows

The right path to fsc.exe etc. on 32-bit Windows

---

guides/cloud/index.md

Apache Storm: ecosystem and great F# support. Placing next to Hadoop, because Storm can share the infrastructure and complement Hadoop's batch processing with event-streaming capabilities.

Added a few references about Apache Storm

---

use/linux/index.md

Since instructions for various Debian/Ubuntu versions vary and they
are described in Mono Documentation, I just removed old instructions
which were not accurate for recent Debian (jessie) and replaced it
with direct link to Mono Documentation.

Update of documentation for Debian/Ubuntu.

---

use/mac/index.md

Homebrew installs a 64-bit version of Mono. Running ```mono --version``` prints ```Architecture: amd64``` in all my test systems after using homebrew to install it.
Furthermore, Xamarin seems to work great with this installation and it can run and debug 64-bit projects as long as I add this runtime to the .NET Runtimes.
This is a friendly suggestion to update the help page.

Homebrew installs 64-bit and Xamarin can use it.

---

guides/mac-linux-cross-platform/index.md

Copying and managing fsproj files by hand does not work very well in
practice, so I think recommending forge is a reasonable alternative for
now, until dotnet cli becomes the way to go.

Include Forge in Cross Platform Tooling

---

css/main.css

Negative margin on H1-H5 headers caused that previous (upper) html content is overlayed by header and links are not clickable on mobile devices.

Fixed unclickable links on mobile devices (negative margin overlays upper content)

---

use/html5/index.md

I recommend that the "use" guides not include options labelled as not being actively maintained.  The "community/projects" list can include such projects.

Adjust HTML5 "use" guide

---

use/linux/index.md

Apparently 7 blank chars is what's needed to get the code block to works within lists.
Thanks @danbst for noticing (https://github.com/fsharp/fsfoundation/pull/589#issuecomment-242922845)

fix numbering and long lines in nix section

---

specs/component-design-guidelines/index.md

Added general guideline re. cultural processing of strings.  This is an
extremely cut-down version of my original contribution to the
`Recommended Guidelines for F# Projects, Packages and Namespaces`
document of the F# Core Engineering Group, from 2014.

Added guideline re. cultural processing of strings

---

use/mac/index.md

I'm not sure exactly what's going on at the fsharp.org rendering; however, there is an extra space at: http://fsharp.org/use/mac/
ext install Ionide-fsharp
As a complete noob to VSCode, I was confused why the copy-paste didn't work as expected.  Hopefully this will help.

Remove superfluous space

---

use/freebsd/index.md

There is no longer a need to adjust the permissions on the Mono registry folder, and it doesn't exist anymore whether installing from pkg or ports.

Remove the section about the Mono registry folder

---

learn.md
use/linux/index.md

Updates instructions for using FSharp on CentOS/RHEL etc. to point to official mono-complete and fsharp packages.
Fixes #611

Update instructions for using fsharp on centos

---

community/projects/index.md

Don't want to conflict with the diagramming tool of the same name.

Renamed FlowSharp to FsDecider

---

guides/data-science/index.md
guides/machine-learning/index.md
index.html
learn.md
teaching/index.md

I think it's time to let go of tryfsharp.org. It requires you to install Silverlight, an outdated browser plugin, which may put off potential new F# users.
Ideally the site itself should be updated to not require Silverlight or taken down.

Remove references to tryfsharp.org

---

js/home.js

This was causing large blocks of raw HTML to display in the feed - right now, it should just display the title.

Commented out feed entry content

---

use/windows/index.md

Updated guidance and links for the new F# 4.1 Compiler SDK download.  Moved 4.0 and 3.0 down.  Added section of VS 2017 Build Tools SKU, as F# will be a part of this starting with Update 3.

Update using on Windows

---

guides/mac-linux-cross-platform/index.md

The current link to forge points to a non-existent repository.

Updated dead forge link

---

use/linux/index.md

For a long time I have felt that the "Use F# on Linux" page should be structured a little differently, to be more in line with common practices in the Linux world. Here is my attempt to move this forward a little bit. Specifically:
- For a getting started document, the first sentence shouldn't talk about the Core Engineering Group.
- It seems clearer to me to have the sections ordered differently: Installation on the mainstream distributions, then building from source, then the more esoteric approaches. Followed by a plug for VS Code/Ionide and Rider. Finally, a call to action at the end.
- I took out the references to mono-complete from the package manager instructions, as the fsharp package itself can be expected to pull in the bits of mono that it needs. This saves some 300 MB and …

Reordered and extended F# on linux page

---

use/mac/index.md

Fixes #592 by clarifying how to install mono, which is a prereq for VS Code

Clarify install instructions for VS Code

---

guides/machine-learning/index.md

The math statistics link on the machine learning guide page is broken due to an missing / in the path.

Broken link (math/stats) on ml page

---

use/windows/index.md

The current page has a duplicate link to the 3.0 tools.. This link points to the 4.0 tools. If there's a go.microsoft.com link, use that instead, but this one points to the correct bundle.

Current link points to 3.0 tools.

---

guides/web/index.md

I felt that Giraffe needed its own section, as it is a distinct programming model compared with ASP.NET Core.  I also updated the ASP.NET Core section to mention that ASP.NET Core supports F# out of the box, and has templates.  Updated links.

Update giraffe and aspnetcore

---

use/windows/index.md

The shortcut to open the command panel is `ctrl+shift+p` and `F1`. Personally I prefer to use `F1` but a lot of other tutorials/guides for vs code use `ctrl+shift+p` so I changed to shortcut to that.

fix key shortcut for vs code on windows

---

use/mac/index.md

* Xamarin Studio --> VS for Mac
* Add .NET Core CLI and link to the guide
* Move VSCode to the top
I'd really like this page to be simpler, but I think that will be addressed better by a forthcoming redesign.  In the meantime, here's some updates.

Add .NET Core CLI, remove Xamarin Studio, and re-order things

---

use/android/index.md

1) I put the JetBrains option as the first choice, since its cross-platform and follows the spirit of .NET Core and F# by that.
2) Changed the typo "iOS" into "Android"
3) Removed Xamarin Studio, since it is ditched in favour of Visual Studio exclusively.

Update to the current state (Feb2018)

---

_layouts/default.html

Update the site footer's copyright year from '2017' to '2018'

---

use/linux/index.md

Since https://github.com/fsharp/fsharp/commit/8a5fa570a0334b073e2ffe8f816b3bf84bdafcee

Autogen no longer used to build F# from source

---

use/mac/index.md

Fixes dead link to mono download in Option #5 of https://fsharp.org/use/mac/
Also updates others that already have the correct target to https.
And `/download/stable/` is what their main page links to, so adjusted to that.

Fix dead mono download link, update others to https

---

use/windows/index.md

There was an inconsistency between the verbiage of "step" versus "option". The instruction to see "step 4" was misleading and saw some issues during a try F# workshop.

update windows install docs step vs option

---

guides/apps-and-games/index.md

@ReedCopsey I thought this might be a valuable example to add. SDL2 direct from F# is quite neat :) And a lot lower friction (subjectively) than using a larger framework, like MonoGame or Unity.

Added a F#+SDL2 demo

---

_layouts/default.html

This should fix the year for all markdown-generated templated pages

Update the footer year for generated markdown

---

use/windows/index.md

Bringing https://fsharp.org/use/windows/ up to date
Initial changes:
Visual Studio 2017-19 (and deleted very old versions)
Deleted "Older F# installations"

Update Using F# on Windows

---

learn.md

When I Google "try f#" the first hit is https://fsharp.org/learn.html, which is great. But there is no link to https://try.fsharp.org/ there. Please add it.
TODO: Add a link to https://www.codewars.com, which includes katas for F#.

Adding TryFSharp

---

guides/data-science/index.md

I – found two typos («pa**cak**ges» and «pro**vids**»), edited them (both; in-to: «pa**cka**ges» and «provid**e**s», – re-spectively), – and – provided a «changed» version (of – the file)… Would you like – to use, the proposed?

Typos in “index.md”

---

guides/web/index.md

Finding a hosting service which support .NET Core and is free is an easy task. I'd like to share with GearHost as it may fit needs of many F# developers, looking for free option to host their small websites. I've managed to host applications based on various web frameworks: ASP.NET Core (F# template), Suave, Giraffe (MVC template) or Freya.

Add GearHost as hosting provider

---

teaching/index.md

Link to "Functional Programming with F#" course was broken. Updated with current version of web page.

Update link to "Functional Programming with F#"

---

use/linux/index.md
use/mac/index.md

Rider now no longer requires Mono on macOS or Linux

Update for Rider 2020.1

---

use/linux/index.md

Obviously we don't have that on Linux.

Remove VSCode "for macOS" text from Linux usage.

---

use/mac/index.md

The default keyboard shortcut to invoke the Command Palette on mac is Cmd+Shift+P, not Ctrl+Shift+P.

Update keyboard shortcut in use section for mac

---

guides/web/index.md

This was targetting "old" ASP.Net, we shouldn't really promote it any more

Remove Pure F# Web API 2.0 from web guide

---

_layouts/default.html
index.html

This aligns the "Foundation" entries more definitely with the foundation.fsharp.org, per issue https://github.com/fsharp/fsfoundation/issues/707
It's not perfect but not too bad.

align foundation entries

---

about/index.md
learn/index.md

@cartermp and I did an assessment last night of all the best core "landing pages" for F# and the traffic they're getting stating from basic searches for things like "Learn F#" on Google.
One thing we noticed is that the really good page https://dotnet.microsoft.com/languages/fsharp is not getting much traffic since there are few links in to it.
This is a good, clear neutrally presented resource that really orients people to the basics of F#'s existence as a modern .NET language. I do think it deserves a higher prominence in the learning and about pages.
This resource does not cover everything and we need to make sure we continue to maintain good balance in the learning material linked here.  But I think it's a good addition given its quality.

Add learning link

---

_layouts/default.html

Closes #832 by adding a link to the learn menu.

Add link to newly generated FSharp.Core API Docs

---

community/projects/index.md

I've been working on my [Interstellar](https://github.com/jwosty/Interstellar) library for a while, and would love if it could be on fsharp.org. There's a lot more info over at the project repo (but still more docs to come of course).

Add Interstellar to projects page

---

guides/mobile-apps/index.md

Add **Blindfold Chess Training** and **Quantum Puzzle Generator** as _Resource Links_ to the _Mobile Apps_ page.
The applications are created with **Fabulous** and target **Android** and **iOS**.

Add two projects (BCT and QPZ) to mobile-apps page

---

use/browser/index.md
use/web-apps/index.md

Removing a REPL that still used Mono 4.5, and had no educational material
Also Visual Studio Online is noe Github Codespaces

remove a repl

---

guides/data-access/index.md

As requested in https://github.com/fsharp/fsfoundation/pull/908#issuecomment-997170725. Unfortunately I don't have the capacity to go through all the items in the list and consider where they should be based on general polish, stability, activity, etc.
Also moved ADO.NET down since it is not F# specific and, I would guess, the least interesting option for F# devs given the amount of other F#-specific options. But I can revert that if you like (or you can do it yourself, of course).

Move Facil higher up and extend description

---

index.html

At last Dugnad (a long time ago) it was pointed out that the "Getting Started" section was weak, in that it didn't give links to actually get started.
This improves that by making the first two links actual intro tutorials
The "F# for JavaScript" link remains as https://fsharp.org is an asset that emphasises this.

improve getting started links

---

guides/cloud/index.md

FsKafka is the de facto successor to Kafunk
it's a light weight F#-focused wrapper over a supported mainstream library (`Confluent.Kafka`) and is being used and maintained.
Kafunk is an archived and unmaintained top to bottom custom client which has some known issues, but also, critically, does not support modern broker versions.

Replace Kafunk with FsKafka

---

use/mac/index.md

This is a foot-gun - the install docs on learn.ms.com are more comprehensive and we _really_ do not want users installing local versions of the SDK. It's inconsistent in a lot of small ways that I have to wrestle with day-to-day. If we did want to highlight CLI-based installs I'd rather suggest homebrew (even though the homebrew recipe is horrible because it doesn't support side-by-side).

Update index.md to not suggest install-sh for mac

---

index.html

Just a small change to update the year to 2023. 
Edit:  Add copyright year from current date.

Fetch copyright year from current date. With fallback to 2023 if no js

---

_layouts/default.html

Fixed the template as well. So the other pages also get a more correct copyright year.
Should have noticed this and included it with the other PR

Add dynamic copyright to html template

---

learn/index.md

Updated the link of the heading to point to http://fsprojects.github.io/fsharp-cheatsheet/

Update link to F# Cheat Sheet

---

docs/index.md

http://dungpa.github.io/fsharp-cheatsheet/ was returning a 404 Not Found. 
I have updated the links for the cheat sheet section to be the correct links

Documentation - Update cheat sheet links to working links

---

use/linux/index.md

This is a foot-gun - the install docs on learn.ms.com are more comprehensive and we _really_ do not want users installing local versions of the SDK. It's inconsistent in a lot of small ways that I have to wrestle with day-to-day. Since the SDK is available in many package managers now by default we should lean into that mechanism.

Don't suggest the install-scripts for linux

---

use/browser/index.md
use/web-apps/index.md

The version of the REPL at `/repl3` no longer works.

Update Fable REPL urls

---

_layouts/main.html

Unpkg is down and seems to have been having trouble for several hours now.
Unfortunately I used unpkg links for some libraries I added recently.
This PR migrates those links to jsdelvr as an interim fix until I can host those libs on the site.

Migrate unpkg links to jsdelivr

---

README.md
_config.yml
_includes/navbar.html
_layouts/main.html
_snippets/aoc_day1.md
_snippets/computation_expressions.md
_snippets/domain_modelling.md
_snippets/fable.md
_snippets/helloworld.md
_snippets/oop.md
_snippets/typeproviders.md
_snippets/unitsOfMeasure.md
css/main.css
css/monokai.css
index.html

Added a code snippet carousel to home page.
I shared this around a bit on Bluesky and the reception was positive. One person was perhaps not sure if the "Fable" example really belonged.
I've used a Jekyll collection for the code snippets (+ accompanying explanatory markdown), so it will be straiigtforward for others to add, remove, or update the snippets.
I've added some notes to the README about this.
Can be previewed at https://ianwitham.github.io/fsharp.org/

Code snippet carousel

---

_snippets/aoc_day1.md
_snippets/async_expressions.md
_snippets/computation_expressions.md
_snippets/domain_modelling.md
_snippets/fable.md
_snippets/helloworld.md
_snippets/oop.md
_snippets/sequence_expressions.md
_snippets/typeproviders.md
_snippets/unitsOfMeasure.md

@IanWitham I've split the computation expression sample into three, and tweaked some of the rest to make the messaging tighter (e.g. use "you" to address the person reading and why it matters to them)

Tweak samples

---

learn/index.md

At the time of this commit, the old link appears to redirect to a spam website.

Update link for the book F# Applied II

---

_testimonials/jozef-rudy.md

new testimonial

---

README.md
community/projects/index.md
guides/cloud/index.md
guides/data-access/index.md
guides/data-science/index.md
guides/engineering/issues.md
guides/enterprise/index.md
guides/mobile-apps/index.md
guides/web/index.md
teaching/research.md

@dsyme That's basically follow-up of the rename of the `gh-pages` branch you already did.

Remove/update mentions of gh-pages branch

---

.editorconfig

VS Code respects this out-of-the-box, so it should help us prevent common problems like:
- Windows line endings
- trailing space
- tabs used for indentation
As I'm using a different editor and Unix, I see a lot of space-related issues in the code, so I'd love for us to clean those up. E.g. that's how the Windows line endings show up on Unix:

Add an .editoconfig file

---

_includes/navbar.html

As discussed earlier. It looks like this now:
The submit link simply points to the README instructions here https://github.com/fsharp/fsharp.org/tree/main?tab=readme-ov-file#testimonials

Move testimonials to a dedicated navbar item

---

robots.txt

Google recommends referencing sitemap from robots.txt

Add YAML front matter to robots.txt and ensure proper sitemap reference

---

teaching/research.md

Delete a duplicate entry in the documentation for the F# Computation Expression Zoo paper.

Remove duplicate entry for F# Computation Expression Zoo paper

---

.markdownlint-cli2.jsonc

I had missed the `config` key and the configuration was completely useless because of this. My bad!

Fix markdownlint configuration

---

guides/data-access/index.md

DbFun is successor of SqlFun, made by the same author, with the same design decisions in mind, but more powerful and more internally consistent.

Replacing SqlFun with DbFun

---

.devcontainer/devcontainer.json
README.md

Don't fix version in devcontainer.json
