fsharp/fsharp.org

css/main.css, index.html, js/home.js
Required for inurement requirements.
=> Removed links from supporters

_layouts/default.html, index.html, specs/component-design-guidelines/index.md
to be standardized and contain 2015 copyright dates, given that it's now
2015.
=> Updated copyright lines

_layouts/default.html, index.html
in the Top navigation structure.
=> Added announcements to Foundation 

testimonials/index.md
see https://twitter.com/dsyme/status/577059819103846400
=> Sync.Today added

guides/web/index.md
Hi,
I have added my blog post series on Web application development in F# under tutorials section.
I feel it would help people who are coming new to F# Web application development.
Let me know if I need to modify any.
Regards
Tamizh
=> Adding Web Application Development in F# tutorial

css/main.css
This should fix the problem without having to edit the page itself.
=> Fix navbar over anchor on the testimonials page

guides/apps-and-games/index.md, testimonials/index.md
Cleaned up mobile guide, updated links, flushed out content
=> Reworking of mobile guide

guides/enterprise/index.md
Purpose of this new page is remove the dependency on an external link.
Note: I did not update the main menu to point to this page. That can be done when this page is approved.
=> Added guides/enterprise page

training/index.md
=> Add GROSSWEBER training

community/projects/index.md, guides/mac-linux-cross-platform/index.md
Re. https://twitter.com/dsyme/status/612034822236672000
Couldn't find any long instructions needing changing, so I've made minor adjustments.
=> minor fixes regarding sublime text

testimonials/index.md
Sorry, I took another testimonial as a model and forgot to update the side quote. Can you please accept the PR to fix the issue?
=> Fix side quote of Green Eagle testimonial

testimonials/index.md
This is to fix a problem created by my previous PR preventing the display of the testimonials
=> Fix invisible starting char in testimonials/index.md

training/index.md
Add new Pluralsight course F# Jumpstart
=> Add F# Jumpstart

guides/cloud/index.md
Orleans samples moved from codeplex to github.
=> Updated Orleans sample url

README.md
Just a minor change to add the link to the F# Foundation web site
=> Added a link to fsharp.org

community/projects/index.md
Link to YaccConstructor project fixed
=> Link to YaccConstructor project fixed

use/windows/index.md
These seem to be necessary on machines without a Visual Studio Installation
=> Added link to build tools

about/learning.md
Multi-Paradigm Programming Using F# and .NET
=> add new book

guides/web/index.md
Actually, the website of Frank seems dead.
=> fix frankfs link

_layouts/default.html, index.html
=> Html5 warnings

guides/math-and-statistics/index.md
Removed FCore from commercial math software, add FCor as open source math software
=> Updated FCor math library info

guides/math-and-statistics/index.md
Fmat and FCor are no longer available
=> Removed Fmat and FCor

community/projects/index.md
I've just put them at the top of the lists which seemed most appropriate, but I won't be offended if people think they're better placed elsewhere!
=> adding aether and chiron to community/projects

community/projects/index.md
(We could add an image as well https://raw.githubusercontent.com/Spreads/Spreads.Docs/master/img/ZipN.png)
=> Add Spreads

mentorship/about.md, mentorship/index.md, mentorship/register.md
Main page broken into three parts. Added status of program to main page.
Reviewed and approved by Andrea.
=> Update of Mentorship program pages, with status update.

mentorship/about.md, mentorship/index.md, mentorship/register.md
Fixed #523. Corrected broken links and added email address.
=> Fixed #523. Corrected broken links and added email address.

teaching/research.md
Add diploma thesis on MBrace in Publications
=> Add MBrace publication

guides/web/index.md, use/html5/index.md, videos/list.json
I’m also deleting the links to my old FunScript videos as they’re not maintained any more.
=> Add Fable to Use guides

testimonials/index.md
new testimonial was indented and interpreted as code
=> wrong indentation

testimonials/index.md
for the sidebar quote to render properly, it looks like.
=> extra line-break needed

community/projects/index.md
Also fixed a typo and updated the links to some projects that have added a nicer landing page
=> Add XPlot and Fable to the community project list, nicer landing pages on some projects, fix typo

guides/data-science/index.md
Removed a dead link from the Matlab section.
Updated mathematica link.
Added Wolfram language link
=> Update data-science index.md

guides/web/index.md, use/html5/index.md
=> Indicate that FunScript is not currently maintained

guides/mac-linux-cross-platform/index.md
Various revisions to the cross-platform guide.  This really needs regular expert QA by someone using F# on Linux/Mac.
=> Updates to cross-platform guide

css/main.css, index.html
Too many important things were pushed down due to dead space
=> Style changes to pull up the fold on main page

use/mac/index.md
Added an extra step to make it clearer
=> Updated steps for VS Code

community/projects/index.md
It's a small tool to help do what Elm package does: bump version based on public surface changes
=> Adding SemVer.FromAssembly

guides/mac-linux-cross-platform/index.md
Taking a pass over this document to update the information in a few places.
=> Updated information on PCLs etc.

guides/web/index.md
Various revisions to modernize the web guide a bit
=> Revise web guide

use/mac/index.md
Reverts fsharp/fsfoundation#603
=> Revert "Remove superfluous space"

guides/cloud/index.md
Link to a template repo & guide for running F# on AWS Lambda
=> Added guide on running F# on AWS Lambda

index.html
Added google analytics event tracking of click events on the homepage.
This should give us a better view in GA how the homepage is currently being used.
=> Home - google analytics event tracking

use/gpu/index.md
Would be nice to update the page
=> updated links and added more features to Alea GPU

use/gpu/index.md
As described here: https://github.com/fsharp/fsfoundation/issues/617
=> Remove dead link

_layouts/default.html, index.html
Adjusted the copyright for _layout/default.html and index.html
=> Adjust copyright #627

guides/web/index.md
Primarily adds https://github.com/jakkaj/aspnetcore_fsharp_docker as a resource
=> Updates to web guide

build.fsx, js/home.js, paket.lock
rewrote news feed using https://rss2json.com/ open api as google's feed api has been deprecated.
fixes #638 
fixes #621
=> Fixed RSS news feed

_layouts/default.html, index.html
=> Fixed twitter links

community/projects/index.md
FSharp.Formatting used an old link.
=> Fixed dead link

guides/web/index.md
=> use anchor class in web guide

css/main.css
The headings are very cramped on the guides
=> Put a little margin above headings

use/linux/index.md
=> Fix anchors and links in use/linux

mentorship/about.md, mentorship/index.md, mentorship/register.md
Okay this are my proposed changes, any comments on this?
cc @selketjah, @ReedCopsey,
=> Preparing for the next mentorship round!

community/projects/index.md
=> Fix community project link for Frank

mentorship/index.md, mentorship/register.md
added survey link and end date
=> updated index and register page that sign up is open with end date

index.html
collapsed the rows from 3 to 2 to preserve space
=> Remove Tachyus and Cumps Consulting from Sponsors

use/windows/index.md
I noticed this download link in the powershell instructions was served over http:// and I noticed it also works over https://
=> This download works fine over https

use/html5/index.md
Elm is currently the most convenient way to do front-end development, so I add it to this section. 
This commit also updates Coffeescript to Livescript, since the second one is the follow-up project of the original inventor of Coffeescript and makes the whole section a bit more generic.
=> Update web development page

guides/web/index.md
=> Fix fable docs link

mentorship/about.md, mentorship/index.md, mentorship/register.md
Updated the text for the 4th mentorship round.
=> update mentorship information for 4th round in February

mentorship/about.md, mentorship/index.md, mentorship/register.md
added all the information to register for the 4th round
=> open registrations for 4th round

learn.md
This might be one of the best ways to build F# skills.
=> Add EXERCISM to learn.md

guides/data-science/index.md
I want to share FSharp.Plotly with the awesome F# community. It is a charting library on top of plotly.js that I am supporting for two years now. It comes with examples and a Nuget package.
As this is my first step here, I hope I did everything correctly.
Thanks a lot for your great work with F# ...
=> Update index.md by adding FSharp.Plotly for graphing

mentorship/about.md, mentorship/index.md, mentorship/register.md
Closed registrations for 4th round
=> close registrations for 4th round

guides/data-science/index.md
Some components related to FsLab have moved
=> Update some links

community/projects/index.md
In the list of community projects:
* adjusted the fslab links
* removed a couple of very old links 
* added a link to https://github.com/fsprojects/awesome-fsharp
=> Update some links and adjust some resources

guides/apps-and-games/index.md
Thought these two projects of mine would make fine sample projects for the site. They are both under Unilicense
=> Added tetris and miniknight to guides

use/windows/index.md
Remove a lot of cruft and simplify the options. Also add F# 4.1 to older F# versions list.
=> Update Windows install page

community/projects/index.md
Adding RemarkFS project - an F# Markdown slide creation tool based on Remark
=> Adding RemarkFS

mentorship/index.md, mentorship/register.md
update information to register for Mentorship round 6
=> open mentorship round 6

index.html
Hi, I'm not super familiar with the F# Software Foundation, but looks like the copyright years should be updated to 2019, right?
=> Update index.html to bump the copyright years.

mentorship/index.md, mentorship/register.md
update index and register with the information that the round is closed and when a new round starts
=> close mentorship round 6

about/index.md
Removed core reference until it becomes unbroken.
=> updated language reference to correct link

about/index.md
=> Removed comment AND broken link

index.html
Changed the verb from 'join' to 'forums'.
=> Added forums link (slight variation on victor's)

guides/web/index.md
=> Add Bolero

_layouts/default.html
Broken links make working links look bad.
=> Removed broken link

_layouts/default.html
=> Moved speakers program to contribute

.gitignore, mentorship/index.md, mentorship/register.md
Updates the mentorship pages for the 2019 Fall mentorship round
=> Updates mentorship information for Fall 2019

guides/enterprise/index.md
If you go to that link, you'll know what I mean.
=> Removing spam link from enterprise guide page

community/projects/index.md
Add SqlFun to Community Projects/Data Access
=> Add SqlFun

community/projects/index.md
MbUnit isn't supported anymore since FsUnit v3.6.0.
=> Remove MbUnit from FsUnit in index.md

guides/machine-learning/index.md
Synapses
A lightweight Neural Network library, for js, jvm and .net
https://mrdimosthenis.github.io/Synapses
=> Add Synapses as a machine learning Package

community/projects/index.md
Fixing 404 link for Frank community project
=> Fixing 404 link

learn/index.md
Following this call to action (https://twitter.com/dsymetweets/status/1250774673069146112) I decided to include this here, in case it helps anyone.
=> learn: add csharp2fsharp tutorial

community/projects/index.md
[Donald](https://github.com/pimbrouwers/Donald) - An idiomatic F# interface for ADO.NET.
[Falco](https://github.com/pimbrouwers/Falco) - A functional micro-library for building brilliant ASP.NET Core applications using F#. Possesses a low barrier to entry for those new to functional programming.
=> donald and falco added to community projects

use/windows/index.md
=> Fix typo Stusio to Studio

learn/index.md
[Learn X in Y Minutes](https://learnxinyminutes.com/) is another good place to start and check out basic features
=> add learn-x-in-y-minutes entry

_layouts/default.html, css/main.css, foundation.html, foundation/index.html, foundation/logo.html, guides/engineering/issues.md, guides/enterprise/index.md, guides/slack/index.md, history/hopl-final/bib.bib, index.html, mentorship/index.md, mentorship/register.md, sitemap.xml, technical-groups/index.md, testimonials.json
For #850 
Find and replace of http://foundation.fsharp.org and http://community.fsharp.org
=> Update foundation and community links to https

learn/index.md
Makes it easier for beginners to discover other options.
=> Add link to Use F# in the browser

community/projects/index.md, guides/data-access/index.md, guides/enterprise/index.md
FSharp.Data has moved to fsprojects
=> Fixing links

use/browser/index.md
=> Reorder websites based on F# version support

community/projects/index.md, guides/cloud/index.md, guides/data-science/index.md
Fixes https://github.com/fsharp/fsfoundation/issues/881
=> cleanup dead links

testimonials/index.md
Testimonial provided by Urs Enzler, with permission per email sent to board@fsharp.org
=> Calitime tesimonial

testimonials/index.md
And also reflect the fact that we have transitioned from startup- to scale-up in the years since the testimonial was submitted.
=> Reflect company name change from Grean to Criipto

guides/data-access/index.md
Coming from this [tweet](https://twitter.com/dsymetweets/status/1459473808834936832) to make sure the SQL and NoSQL Data Access section is not missing some libraries
=> Update Data Access Page

mentorship/index.md, mentorship/register.md
Currently missing the updated link for the registration form. I'll take care of it shortly.
=> Updated content for mentorship round #12.

use/linux/index.md
=> update naming to .NET

use/linux/index.md, use/mac/index.md
- Update install instructions for Mac
- Update install instructions for Linux
=> Update .NET SDK install instructions for Unix systems

guides/data-science/index.md
Adds a short section to describe [Sharp Cells](https://www.sharpcells.com/). 
Disclosure: This is my project so apologies if it reads too much like advertising. Happy to make any necessary edits.
=> Add Sharp Cells to the Excel Interop section

community/projects/index.md, guides/mobile-apps/index.md, use/mobile-apps/index.md
Links to fabulous were not working. This should fix them.
=> fixed broken links to Fabulous

community/projects/index.md
View here: https://fsharpest.xyz/
=> Add FSharpest as a catalog

_includes/navbar.html, _layouts/main.html, css/main.css, index.html, package-lock.json, teaching/research.md, use/mac/index.md
Choose some new fonts: Roboto for headings and Inter for the rest of the text. Can be previewed here: https://ianwitham.github.io/fsharp.org/
Removed x.com links.
Removed "unaffiliated" tags.
Restored how to reference f# link to the "publications" page.
Removed links to User Groups and Speakers Programs links.
Removed the "Visual Studio for Mac" instructions.
Note, I've also removed the "Member Roster" link entirely for now, as the link on foundation.fsharp.org also seems to be dead.
=> Various suggested changes

_includes/navbar.html, index.html
The FSSF is kind of moribund and the moment (will chase for info), so it's not appropriate to have donation or joining links right now, though the other links are still there.
=> Remove some links 

specs/language-spec/index.md
@dsyme Here you go. 
I also took the liberty to fix some markdown spacing and add a link to `fslang-spec`, so it's a bit more visible.
=> Lang spec improvements

index.html
Consider this both a small change and a proposal for a bigger one.
Basically the HTML code in most HTML files is formatted pretty badly and is hard to understand because of this. I've formatted the index.html using the popular tool `prettier` as an example for what we should probably do for all HTML files.
=> Improve the formatting of the index page

index.html
=> [Fix #973] Rename sponsors section

_includes/navbar.html
Resolves fsharp/fsharp.org#984
=> Add LinkedIn link to the navbar

LICENSE, README.md
Another small task completed. :-)
=> [Fix #982] Specify the license

teaching/research.md
Tiny changes, big diff. :D 
@IanWitham I was also thinking we can convert the Papers page to the same format as the books, as it doesn't look very nice right now.
=> Fix links and formatting

_testimonials/jimmy-byrd-1.md, _testimonials/jimmy-byrd-2.md, index.html
=> Add two persuasive quotes by @TheAngryByrd
